table 'Fact TBL PenRate Cumulative'
	lineageTag: fba1a795-4078-4891-b676-9819fb180e13

	column 'Customer Segment'
		dataType: string
		isHidden
		lineageTag: 02e397a1-477e-4eb1-a039-6ef708b685d5
		summarizeBy: none
		sourceColumn: Customer Segment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'HPE accounts '
		dataType: double
		lineageTag: 95742349-6a32-4266-8bd6-e5eb00cb8edd
		summarizeBy: sum
		sourceColumn: "HPE accounts "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Existing GL Accounts'
		dataType: double
		lineageTag: a90abe1f-81f3-4282-9324-76159cbef510
		summarizeBy: sum
		sourceColumn: Existing GL Accounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GL Pen % '
		dataType: double
		lineageTag: 29fe9489-d2d2-416c-bc40-db05d4c46fe8
		summarizeBy: sum
		sourceColumn: "GL Pen % "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Target
		dataType: double
		lineageTag: aa782b4d-fbf8-4c82-8ab3-2b507ce151aa
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Target_Count
		dataType: double
		lineageTag: 08cb36b5-8868-4811-b1b1-a8e980026644
		summarizeBy: sum
		sourceColumn: Target_Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pen Target'
		dataType: double
		lineageTag: 59670f6d-d92a-48e5-8645-b21f53d545a3
		summarizeBy: sum
		sourceColumn: Pen Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Count_ST_ids
		dataType: double
		lineageTag: b42c23b1-6923-4bb2-9e93-970a4431c321
		summarizeBy: sum
		sourceColumn: Count_ST_ids

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Top_ST_ids_Count
		dataType: double
		lineageTag: 121a1f1c-bf6e-415d-9923-6d3c313fc941
		summarizeBy: sum
		sourceColumn: Top_ST_ids_Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coverage Segments Rank'
		dataType: int64
		formatString: 0
		lineageTag: da80ee2a-d8a8-4ff3-8c30-859e97a97ad1
		summarizeBy: sum
		sourceColumn: Coverage Segments Rank

		annotation SummarizationSetBy = Automatic

	column MDM_HPE_Accounts
		dataType: double
		lineageTag: 48547a4d-18c6-40a8-99b2-d0308a9be360
		summarizeBy: sum
		sourceColumn: MDM_HPE_Accounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Target_Count_TOTAL
		dataType: double
		lineageTag: dda1935b-8af8-49cb-bed0-bb31cd03593a
		summarizeBy: sum
		sourceColumn: Target_Count_TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date_KY
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 7c265e79-5a8e-4c10-b2b7-02ca5f1cd050
		summarizeBy: none
		sourceColumn: Date_KY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Geo_Ky
		dataType: string
		lineageTag: d770131d-f35f-4ed4-a250-60206551cd87
		summarizeBy: none
		sourceColumn: Geo_Ky

		annotation SummarizationSetBy = Automatic

	partition 'Fact TBL PenRate Cumulative-01aaaa2b-a952-49ff-95bb-e37e896c28c7' = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = Sql.Database(DataSourceParam, DBName, [CommandTimeout=#duration(0, Timeout, 0, 0)]),
				    dbo_REP_TBL_PenRate_Cumulative_Visual = Source{[Schema="dbo",Item="REP_TBL_PenRate_Cumulative_Visual"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_REP_TBL_PenRate_Cumulative_Visual,{"Customer Segment", "HPE accounts ", "Existing GL Accounts", "GL Pen % ", "Target", "Target_Count", "Pen Target", "Count_ST_ids", "Top_ST_ids_Count", "Coverage Segments Rank", "MDM_HPE_Accounts", "Target_Count_TOTAL", "Date_KY", "Geo_Ky"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

